version: '3.9'
services:
  backend:
    container_name: food-monks-backend
    image: 711621010839.dkr.ecr.us-east-2.amazonaws.com/foodmonks-dev-backend:dev-latest
    build: 
      context: ../backend
      # dockerfile: ../../docker/backend/Dockerfile
    ports:
      - "9001:9001"
    env_file:
      - .env_java
    restart: always
    networks:
      - foodmonks-net

  frontend:
    container_name: food-monks-frontend
    build:
      context: ../frontend
      # dockerfile: ../../docker/frontend/Dockerfile
    image: 711621010839.dkr.ecr.us-east-2.amazonaws.com/foodmonks-dev-frontend:dev-latest
    ports:
      - "8080:80"
    env_file:
      - .env_react
    restart: always
    networks:
      - foodmonks-net

networks:
  foodmonks-net:
    driver: bridge
    name: foodmonks-net